CREATE TABLE IF NOT EXISTS EVENTS (
  ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
  state    INTEGER,
  document LONGTEXT
);

CREATE TABLE IF NOT EXISTS PROJECTS (
  ID       VARCHAR(1000) PRIMARY KEY,
  NAME     VARCHAR(100),
  document LONGTEXT
);

CREATE TABLE IF NOT EXISTS TABLES (
  ID       VARCHAR(1000) PRIMARY KEY,
  NAME     VARCHAR(100),
  document LONGTEXT
);

CREATE TABLE IF NOT EXISTS API (
  ID        VARCHAR(1000) PRIMARY KEY,
  FULLURL   TEXT,
  IDPROJECT VARCHAR(1000),
  document  LONGTEXT
);


CREATE TABLE IF NOT EXISTS VERSIONS (
  ID        VARCHAR(1000) PRIMARY KEY,
  IDPROJECT VARCHAR(1000),
  NAME      VARCHAR(200),
  document  LONGTEXT
);
